export const TeamData = [
  {
    id: 1,
    name: "Serah Muthoni KAMAU",
    role: "Founder & CEO",
    country: "Kenya",
    bio: "Passionate visionary committed to innovation and excellence. Leading the way towards a brighter future.",
    img: "/Assets/BigImages/avatar1.png",
  },
  {
    id: 2,
    name: "Soraya Haidary",
    role: "CTO",
    country: "Afghanistan",
    bio: "Technology virtuoso leading with innovation and determination. Pioneering advancements in tech with a global perspective.",
    img: "/Assets/BigImages/avatar5.png",
  },
  {
    id: 3,
    name: "Esther Wangui Gicheha",
    role: "Supervisor/Executive Assistant",
    country: "Kenya",
    bio: "Dedicated supervisor and executive assistant. Facilitates smooth operations with efficiency and attention to detail.",
    img: "/Assets/BigImages/esther.jpeg",
  },
  {
    id: 4,
    name: "Alphonsus Chioma Tracy",
    role: "Project Manager",
    country: "Nigeria",
    bio: "Organized and strategic project manager with a relentless focus on delivering successful outcomes. Turning challenges into triumphs with a structured approach.",
    img: "/Assets/BigImages/tracey.jpg",
  },
  {
    id: 5,
    name: "Aenia Amin",
    role: "Data Analyst",
    country: "USA",
    bio: "Experienced developer with a talent for transforming concepts into reality. Harnessing the power of data to drive informed decision-making.",
    img: "/Assets/BigImages/Aenia.jpeg",
  },
  {
    id: 6,
    name: "Kosisochukwu Benjamin",
    role: "IT Security Specialist",
    country: "Nigeria",
    bio: "Analytical thinker skilled in deciphering complex datasets. Ensuring the fortification of our digital infrastructure with top-notch security measures.",
    img: "/Assets/BigImages/benjamin.jpg",
  },
  {
    id: 7,
    name: "Cassandra Lelei",
    role: "Lead Software Developer",
    country: "Kenya",
    bio: "Creative powerhouse spearheading software development with precision and innovation. Ensures seamless project execution.",
    img: "/Assets/BigImages/avatar3.png",
  },
  {
    id: 8,
    name: "Mary Wanjiru kaberia",
    role: "HR Manager",
    country: "Kenya",
    bio: "Our HR Manager fosters a thriving workplace with efficiency and empathy",
    img: "/Assets/BigImages/HR.jpg",
  },
  {
    id: 9,
    name: "Emuesiri Ekevwe",
    role: "social media manager",
    country: "Nigeria",
    bio: "Lead our company's social media presence with strategic planning and engaging content creation.",
    img: "/Assets/BigImages/avatar6.png",
  },
  {
    id: 10,
    name: "Akinsanya oluwatosin",
    role: "product manager",
    country: "Sout Africa",
    bio: "Our product manager oversees the developmentand enhancement of our company's offering",
    img: "/Assets/BigImages/product.jpg",
  },
  {
    id: 11,
    name: "Teslimah Salahudeen",
    role: "Cyber Security",
    country: "Nigeria",
    bio: "Seasoned cyber security expert dedicated to protecting digital assets and ensuring data privacy. Passionate about leveraging advanced technologies to safeguard organizations against evolving cyber threats.",
    img: "/Assets/BigImages/Salahudeen.jpeg",
  },
];
