export const TeamData = [
  {
    id: 1,
    name: "Serah Muthoni KAMAU",
    role: "Founder & CEO",
    country: "Kenya",
    bio: "Passionate visionary committed to innovation and excellence. Leading the way towards a brighter future.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/avatar1.png",
  },
  {
    id: 2,
    name: "Soraya Haidary",
    role: "CTO",
    country: "Afghanistan",
    bio: "Technology virtuoso leading with innovation and determination. Pioneering advancements in tech with a global perspective.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/avatar5.png",
  },
  {
    id: 3,
    name: "Esther Wangui Gicheha",
    role: "Supervisor/Executive Assistant",
    country: "Kenya",
    bio: "Dedicated supervisor and executive assistant. Facilitates smooth operations with efficiency and attention to detail.",
    img: process.env.PUBLIC_URL +  "/Assets/BigImages/esther.jpeg",
  },
  {
    id: 4,
    name: "Alphonsus Chioma Tracy",
    role: "Lead Project Manager",
    country: "Nigeria",
    bio: "Organized and strategic project manager with a relentless focus on delivering successful outcomes. Turning challenges into triumphs with a structured approach.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/tracey.jpg",
  },
  {
    id: 5,
    name: "Aenia Amin",
    role: "Lead Data Analyst",
    country: "USA",
    bio: "Experienced developer with a talent for transforming concepts into reality. Harnessing the power of data to drive informed decision-making.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/Aenia.jpeg",
  },
  {
    id: 6,
    name: "Okoye Blessing",
    role: "Lead Product Manager",
    country: "Nigeria",
    bio: "Okoye Blessing, a visionary Lead Product Designer from Nigeria, crafts impactful user experiences with creativity and precision.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/okoye.jpg",
  },
  {
    id: 7,
    name: "Cassandra Lelei",
    role: "Lead Software Developer",
    country: "Kenya",
    bio: "Creative powerhouse spearheading software development with precision and innovation. Ensures seamless project execution.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/avatar3.png",
  },
  {
    id: 8,
    name: "Mary Wanjiru kaberia",
    role: "HR Manager",
    country: "Kenya",
    bio: "Our HR Manager fosters a thriving workplace with efficiency and empathy",
    img:process.env.PUBLIC_URL +  "/Assets/BigImages/HR.jpg",
  },
  {
    id: 9,
    name: "Nora Oyiengo",
    role: "Lead UI/UX Designer",
    country: "Kenya",
    bio: "Lead UI/UX designer with strategic planning and engaging user interface creation.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/nora.jpg",
  },
  {
    id: 10,
    name: "Beatrice Shabani",
    role: "Lead Graphic Designer",
    country: "Nigeria",
    bio: " Beatrice Shabani is an accomplished graphic designer from Nigeria, leading creative projects with expertise and innovation. Her work demonstrates a keen eye for detail and a passion for visual storytelling, making her an invaluable asset to any design team.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/shabani.png",
  },
  {
    id: 11,
    name: "Teslimah Salahudeen",
    role: "Lead Cyber Security",
    country: "Nigeria",
    bio: "Seasoned cyber security expert dedicated to protecting digital assets and ensuring data privacy. Passionate about leveraging advanced technologies to safeguard organizations against evolving cyber threats.",
    img: process.env.PUBLIC_URL +  "/Assets/BigImages/Salahudeen.jpeg",
  },
  {
    id: 12,
    name: "Jeannette Musabyimana",
    role: "DataBase Administrator",
    country: "Rwanda",
    bio: "Jeannette Musabyimana, a DataBase Administrator from Rwanda, excels in managing and optimizing database systems.",
    img: process.env.PUBLIC_URL + "/Assets/BigImages/janette.jpeg",
  },
];
